import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import styled from "styled-components"


export default function Home() {
  return (
    <StyledMain>
      <Head>
        <title>WhatsApp Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
     
    </StyledMain>
  )
}

const StyledMain = styled.div`
width:100%;
`